services:
  - type: web
    name: dotnet-server
    env: dotnet
    plan: free   # change if needed
    region: oregon # or frankfurt/singapore
    buildCommand: |
      dotnet restore
      dotnet publish -c Release -o out
    startCommand: dotnet out/ManagementApplication.dll
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: "true"
      - key: ASPNETCORE_URLS
        value: "http://+:5000"
